### ISSUE TITLE
Failed caching mapping files

### ISSUE THREAD

**Issue by An1th** [spacetelescope/jwebbinar_prep#121]
While running the imaging_mode_stage_1.ipynb, an error occured in creating an instance of the pipeline class:
Failed caching mapping files: Error fetching data for 'jwst_system_datalvl_0002.rmap' at CRDS server 'https://jwst-crds-pub.stsci.edu/' with mode 'http' : [Errno 13] Permission denied: '/path'
![image](https://user-images.githubusercontent.com/85044324/201685414-bbebe7ae-60e5-43f9-9190-0a4b31aca464.png)

Happy to provide more information if required.

**Comment by bhilbert4** [comment]
Thanks for reporting this. The CRDS PUB server was deprecated last week. Try switching the environment variable in the first cell of the Imports section to be:
os.environ["CRDS_SERVER_URL"]="https://jwst-crds.stsci.edu"

**Comment by An1th** [comment]
Amazing. That did the trick. Thank you
