### ISSUE TITLE
ERROR: Browser 'default' not found. [astropy.table.table]

### ISSUE THREAD

**Issue by cslocum** [spacetelescope/jwebbinar_prep#3]
In jwst-data-products-part3-static.ipynb, I get "ERROR: Browser 'default' not found. [astropy.table.table]" following `image_catalog.show_in_browser()`.

![image](https://user-images.githubusercontent.com/6738995/113749257-76c9be00-96d7-11eb-9cd7-486ded259f55.png)

Note: this is in lab mode.

**Comment by gsnyder206** [comment]
This same issue occurred for me when running in "Notebook" mode

**Comment by cslocum** [comment]
This might be another cell (similar to the one above it, see #5) that we should get rid of.  There is a browser argument to `show_in_browser()`, but we can't make assumptions about what browsers the users will have.

https://keflavich-astropy.readthedocs.io/en/latest/api/astropy.table.Table.html#astropy.table.Table.show_in_browser

**Comment by cslocum** [comment]
BTW - 'default' refers to the default system browser.  I'm not sure how astropy figures out the default system browser, but according to it's logic, neither Greg nor I have a default.

**Comment by cslocum** [comment]
OK, astropy uses [webbbrowser](https://docs.python.org/3/library/webbrowser.html) to determine which browser to use.

**Comment by cslocum** [comment]
This has been fixed.  Can close this.
