### ISSUE TITLE
Javascript Error: IPython is not defined

### ISSUE THREAD

**Issue by cslocum** [spacetelescope/jwebbinar_prep#4]
In jwst-data-products-part3-static.ipynb, I get "Javascript Error: IPython is not defined" following `plot_spectra(spectrum, median_filter=11)`.

![image](https://user-images.githubusercontent.com/6738995/113749712-f0fa4280-96d7-11eb-96df-742ac78d35b9.png)

Note: this is in lab mode.

**Comment by cslocum** [comment]
I also get the same error in multiple places in jwst-data-products-part3-static.ipynb.

**Comment by cslocum** [comment]
Changing `%matplotlib notebook` to `%matplotlib inline` fixes this issue.

**Comment by gsnyder206** [comment]
Interestingly, I had not seen these errors when running this notebook in Notebook mode.

**Comment by cslocum** [comment]
Same - but when I switch to inline, it works in both modes.

**Comment by cslocum** [comment]
Fixed in https://github.com/spacetelescope/jwebbinar_prep/pull/6.
