### ISSUE TITLE
Possible error/performance problem with image_catalog.show_in_notebook()

### ISSUE THREAD

**Issue by gsnyder206** [spacetelescope/jwebbinar_prep#5]
I am seeing possible performance issues with the line `image_catalog.show_in_notebook()` in pipeline_products_session/jwst-data-products-part3-static.ipynb when running in the JWebbinar platform. This cell worked for me in Lab mode, but appears to be causing my Firefox tab to hang indefinitely when running in Notebook mode.  The table appears to be attempting to display the entire thing in the output cell?  Saving the notebook after this cell (in Lab mode) also leads to difficulty/slowness loading the notebook (in Notebook and Lab modes) the next time.

**Comment by gsnyder206** [comment]
From the astropy.Table docs, it looks like "image_catalog.show_in_notebook()" should only display 50 rows by default, but I saw all 6700 in JupyterLab, and this cell did not complete in Notebook/tree mode.  I'm not 100% sure what's going on, but it may be best to simply delete that cell from the notebook, unless it is necessary to display all rows in the output there.

**Comment by aliciacanipe** [comment]
We can delete the cell, I was just trying to show some convenient jupyter functionality but it's not that important. It was more of a "nice to show" cell.

**Comment by cslocum** [comment]
You could also comment out the code in that cell, with a comment that it can be run in Lab mode.

**Comment by camipacifici** [comment]
@aliciacanipe can you please update the notebook to reflect this and submit a new pull request?

**Comment by cslocum** [comment]
@aliciacanipe also see #3 please.  It's related.

**Comment by aliciacanipe** [comment]
I submitted #7 to fix the issues with `show_in_<notebook/browser>`. They're now just markdown examples for user information and not executable cells.

**Comment by camipacifici** [comment]
merged #7. does this fix the problem?

**Comment by cslocum** [comment]
Yes :)
