### ISSUE TITLE
Remaining edits for MRS_Notebook1.ipynb

### ISSUE THREAD

**Issue by ojustino** [spacetelescope/jwebbinar_prep#61]
Since we needed to merge #46 before the completion of the technical review, I am listing the remaining needed edits in this issue. @drlaw1558 has said that late July could be a possible time to get these done.

1. **Complete the data loading procedure.** It's good that we've given the data its own folder on Box and that there's now a note that the notebook will not run without downloading data from Box. The last move is to **make a cell that carries out the download without extra input needed from the user**. It's OK to give the user the option to skip it, but there should be functionality to fetch the data if they choose to run all cells consecutively.
    - (If you're not sure how to download the data within the context of the notebook, see the "Download the data" section of [`nirspec_fs.ipynb`](https://github.com/spacetelescope/jwebbinar_prep/blob/main/spec_mode/nirspec_fs.ipynb) from the same session for an example.) 
2. **Address all remaining PEP8 issues.** @drlaw1558 can either follow the instructions given in this repository's documentation (_link forthcoming_) or open a new pull request where I can add a commit that shows which cells still have issues. You can also view warnings from a previous commit [here](https://app.reviewnb.com/spacetelescope/jwebbinar_prep/commit/b4032ba0ef4cd011fad02e834b94654cfee16c38/).

**Comment by camipacifici** [comment]
@ojustino feel free to close this if it is solved.
